language: cpp
compiler:
- clang
- gcc

before_install:
    - sudo apt update 
    - sudo apt install -y gcc g++ texlive-latex-recommended 
    - sudo apt install cmake 

script:
    - cmake -DCMAKE_INSTALL_PREFIX=/tmp/ahirv2 .
    - make -j3
    - make install
